### ISSUE TITLE
BUG: auto-fold-chat-input-area.css自动吞掉动画未结束前输入的字符

### ISSUE THREAD

**Issue by ikenxuan** [lamprose/transitio-css#1]
- QQNT版本: 9.9.2-16183 (64位)
- LiteLoader版本: 0.5.2
- Transitio版本: 0.3.0
- 状况: 
1. 输入框弹出动画还未结束过快输入时，使用**微软拼音输入法**打字时会自动吞掉前几个已经输入的字符。触发概率: 100%
2. 还有有时候想输入时，但是**输入框不会弹出**。触发时机摸不透，有时从其他应用切换回qq时或者原本就在qq里面什么都不做都有可能会触发
![QQ截图20230823080151](https://github.com/lamprose/transitio-css/assets/112480306/0b477a57-9f68-4981-a348-c19f17351cff)
![image](https://github.com/lamprose/transitio-css/assets/112480306/6770ccee-94a4-4c3e-80b5-226b0b74919a)

**Comment by ikenxuan** [comment]
还有: 
- 当输入框没有输入字符时（只留下光标在闪），输入框不会自动折叠，切换到其他聊天窗口（不管是私聊还是群聊）也不会折叠

希望: 
- 输入框没有键入字符时自动折叠。当然不做也没关系，这并不影响体验

**Comment by yhzcake** [comment]
建议设置成
当输入框未focus时折叠,当鼠标移动到输入框上方工具栏时取消折叠,这时鼠标可以点击输入框进行输入
